### ISSUE TITLE
binary create fails with HTTP 405 -- what am I missing?

### ISSUE THREAD

**Issue by GregMeno** [ceph/chacra#167]
```
(chacra)vagrant@vagrant:~$ pip freeze --version chacractl
argparse==1.2.1
chacractl==0.0.8
requests==2.10.0
tambo==0.2.0
wsgiref==0.1.2
(chacra)vagrant@vagrant:~$ chacra/bin/chacractl binary create calamari/1.4.7/centos/7/x86_64/ calamari-server-1.4.7.rpm 
[requests.packages.urllib3.connectionpool][INFO  ] Starting new HTTPS connection (1): chacra.ceph.com
/home/vagrant/chacra/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/vagrant/chacra/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[requests.packages.urllib3.connectionpool][DEBUG ] "HEAD /binaries/calamari/1.4.7/centos/7/x86_64/calamari-server-1.4.7.rpm/ HTTP/1.1" 404 0
[chacractl.api.binaries][INFO  ] POSTing file: /home/vagrant/calamari-server-1.4.7.rpm
[requests.packages.urllib3.connectionpool][INFO  ] Starting new HTTPS connection (1): chacra.ceph.com
/home/vagrant/chacra/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[requests.packages.urllib3.connectionpool][DEBUG ] "POST /binaries/calamari/1.4.7/centos/7/x86_64/ HTTP/1.1" 405 56
[chacractl.api.binaries][WARNIN] 405 -> {"message": "POST requests to this url are not allowed"}
Traceback (most recent call last):
  File "chacra/bin/chacractl", line 6, in <module>
    main.ChacraCtl()
  File "/home/vagrant/chacra/local/lib/python2.7/site-packages/chacractl/main.py", line 38, in __init__
    self.main(argv)
  File "/home/vagrant/chacra/local/lib/python2.7/site-packages/chacractl/decorators.py", line 68, in newfunc
    return f(*a, **kw)
  File "/home/vagrant/chacra/local/lib/python2.7/site-packages/chacractl/main.py", line 82, in main
    parser.dispatch()
  File "/home/vagrant/chacra/local/lib/python2.7/site-packages/tambo/dispatcher.py", line 21, in dispatch
    return instance.main()
  File "/home/vagrant/chacra/local/lib/python2.7/site-packages/chacractl/api/binaries.py", line 136, in main
    self.post(url, filepath)
  File "/home/vagrant/chacra/local/lib/python2.7/site-packages/chacractl/api/binaries.py", line 82, in post
    response.raise_for_status()
  File "/home/vagrant/chacra/local/lib/python2.7/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://chacra.ceph.com/binaries/calamari/1.4.7/centos/7/x86_64/
(chacra)vagrant@vagrant:~$ 
```

**Comment by andrewschoen** [comment]
I think you might be missing sha1 in your url.  Can you try this?

`chacractl binary create calamari/1.4.7/$SHA1/centos/7/x86_64/ calamari-server-1.4.7.rpm`

Just replace $SHA1 with the appropriate value.
